version: '3'
services:
  todo:
    build: ./backend
    depends_on:
      - todo_db
    environment:
      - DB_URL=postgresql://todo_db/postgres:5432

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/index.js:/usr/app/index.js
    ports:
      - "8000:8000"
    environment:
      - BACKEND_URL=http://todo:5000

  todo_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
