version: '3'
services:
  todo:
    build: ./backend

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/index.js:/usr/app/index.js
    ports:
      - "8000:8000"
    environment:
      - BACKEND_URL=http://todo:5000